Algoritmo "Exercício 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Aldo Henrique
// Descrição   : Lista de Exercício 1
// Autor(a)    : Aline Lopes da Silva
// Data atual  : 01/03/2020
Var
// Seção de Declarações das variáveis 
        N:Inteiro

Inicio
      escreval("digite um número")
      leia(N)
      N<-N*N
      Escreval("o valor do quadrado do numero digitado é", N)

Fimalgoritmo